version: "3.8"
services:
  redis1:
    image: bitnami/redis:7.0.10
    ports:
    - "6379:6379"
    environment:
      - REDIS_MAXMEMORY=1mb
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_MAXMEMORY_POLICY=allkeys-lfu
  redis2:
    image: bitnami/redis:7.0.10
    ports:
    - "6380:6379"
    environment:
      - REDIS_MAXMEMORY=1mb
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_MAXMEMORY_POLICY=allkeys-lfu
  redis3:
    image: bitnami/redis:7.0.10
    ports:
    - "6381:6379"
    environment:
      - REDIS_MAXMEMORY=1mb
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_MAXMEMORY_POLICY=allkeys-lfu
